
logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wx.mp: DEBUG

wechat:
  mp:
    appId:
    secret:
    token:
    aesKey:
server:
  port: 80

token:
  base:
    url:
  username:
  password:
